-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 18:01:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `PNombre` VARCHAR(45) NULL,
  `SNombre` VARCHAR(45) NULL,
  `PApellido` VARCHAR(45) NULL,
  `SApellido` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `FNacimiento` DATE NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Religion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `Pnombre` VARCHAR(45) NULL,
  `Snombre` VARCHAR(45) NULL,
  `Papellido` VARCHAR(45) NULL,
  `Sapellido` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `FNacimiento` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `NombreEspecialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `ClasificacionConsulta` VARCHAR(45) NULL,
  `DescripcionConsulta` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Hora` VARCHAR(45) NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idConsulta`),
  INDEX `fk_Consulta_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Consulta_Medico1_idx` (`Medico_idMedico` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `mydb`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receta` (
  `idReceta` INT NOT NULL AUTO_INCREMENT,
  `Tratamiento` VARCHAR(45) NULL,
  `Costo` INT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Consulta_idConsulta` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idReceta`),
  INDEX `fk_Receta_Medico1_idx` (`Medico_idMedico` ASC) VISIBLE,
  INDEX `fk_Receta_Consulta1_idx` (`Consulta_idConsulta` ASC) VISIBLE,
  INDEX `fk_Receta_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_Receta_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `mydb`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_Consulta1`
    FOREIGN KEY (`Consulta_idConsulta`)
    REFERENCES `mydb`.`Consulta` (`idConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inicio_sesión`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inicio_sesión` (
  `idInicio_sesión` INT NOT NULL AUTO_INCREMENT,
  `Correo` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `TipoUsuario` INT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idInicio_sesión`),
  INDEX `fk_Inicio_sesión_Paciente_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Inicio_sesión_Medico1_idx` (`Medico_idMedico` ASC) VISIBLE,
  CONSTRAINT `fk_Inicio_sesión_Paciente`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inicio_sesión_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `mydb`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
